### ISSUE TITLE
Prisma & Docker integration

### ISSUE THREAD

**Issue by codeYann** [codeYann/ts-prisma-case#5]
# TODO

- [x] Create Dockerfile
- [x] Create Docker compose
- [x] Create postgres database using Docker
- [x] Integrate Prisma and Docker
